server:
  port: 8080
  servlet:
    context-path: /api/basic
    encoding:
      charset: UTF-8
      enabled:
        force: true

spring:

  datasource:
    url: jdbc:mariadb://localhost:3307/basic
    driver-class-name: org.mariadb.jdbc.Driver
    username: basicuser
    password: basic0@

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      #none, update, create
      ddl-auto: update

  spring-doc:
    api-docs:
      groups:
        enabled: true
    swagger-ui:
      path: /swagger-ui.html
      displayRequestDuration: true
      groups-order: DESC

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis
    timeout: 60s
    redis:
      flush-mode: on-save
      #사용자 정의 redis 이름
      namespace: basic:session

